apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: adhocgeet4
 labels:
  app:rsweb1 # this the label of RC not label of pods
spec:
 selector
  matchLabels:
   adhoc: geet4  # here also label of pod
 replicas: 1 # always one pod will be present even in case of current worker node failure
 template: 
  metadata:
   name: mypodrs22  # this will be pod name that will be created by RC
   labels:
    adhoc: geet4
  spec:
   containers:
    - name: geetcxrs111
      image: geetika2000/may2020q1:v1 
      ports:
       - containerPort: 80