apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    adhoc: geetq5
spec:
  replicas: 3
  selector:
    matchLabels:
      adhoc: geetq5
  template:
    metadata:
      labels:
        adhoc: geetq5
    spec:
      containers:
      - name: geetc1
        image: geetika2000/may2020q1:v1 
        ports:
        - containerPort: 80
