apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adhocpod7
    adhoc: geet7
  name: adhocpod7
spec:
  volumes: # this is for creating volume of any type , scope of volume is local pod
  - name: geetvol111  # name of volume
    emptyDir: {}
    
  containers:
  - image: alpine
    name: adhocpod7
    volumeMounts:
    - name: geetvol111 # this vol got created in above section
      mountPath: /mnt/  #this folder will be created automatically for mounting purpose
    command: ["\bin\sh","-c","while true ; do date >>/mnt/adhocoutput.txt;sleep 3;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
